import { Project } from "@/types/content";

export const projects: Project[] = [
  {
    id: "project-001",
    name: "今日状态",
    slug: "today-status",
    status: "done",
    role: "Product / iOS Development",
    type: "ios",
    summary: "一个更轻、更像情绪贴纸的状态记录产品，运行在 Watch 和 iPhone 上。",
    why: "我想把“今天是什么感觉”这件事，做成一种不需要长文本输入的表达方式。",
    problem: "传统记录工具太像任务系统，不适合记录那些转瞬即逝的状态感。",
    highlight: "它更像一张会动的情绪贴纸，而不是一张表。",
    featured: true,
    publishDate: "2026-04-10",
    accent: "yellow",
    coverLabel: "WATCH + IPHONE",
    body: [
      "这个项目的出发点很简单：很多时候我知道自己今天的状态变了，但我不想打开一个严肃的日记工具写半页内容。",
      "所以我把记录动作压缩成一种更轻的反馈，像给今天贴一枚标签。用户不需要整理语言，也不需要解释自己为什么会这样。",
      "如果未来继续迭代，我会把它往更强的节奏感和更温柔的提醒方向推进，而不是增加更多复杂功能。",
    ],
    links: [
      { label: "项目详情", href: "/projects/today-status", kind: "detail" },
      { label: "GitHub", href: "https://github.com/yorickjue", kind: "github" },
    ],
  },
  {
    id: "project-002",
    name: "Flow Patch",
    slug: "flow-patch",
    status: "building",
    role: "Product / UX / Engineering",
    type: "tool",
    summary: "一个把重复脑力流程拆成可复用模块的 AI 工作流实验工具。",
    why: "我不想每次都从头组织一遍自己的思考步骤，尤其是那些明明可以复用的流程。",
    problem: "很多 AI 使用场景并不缺模型，而是缺一个真正顺手的流程结构。",
    highlight: "重点不是更大模型，而是更顺的认知编排。",
    featured: true,
    publishDate: "2026-04-14",
    accent: "red",
    coverLabel: "WORKFLOW / AI",
    body: [
      "这个项目更像工作台，而不是聊天框。我希望把拆问题、聚合上下文、组织输出这些动作做成明确的模块。",
      "它不追求花哨，而是要让人可以稳定复用自己的方法论。",
      "目前还在迭代输入结构和结果回看方式，核心问题是如何做到足够强，但不增加使用负担。",
    ],
    links: [
      { label: "项目详情", href: "/projects/flow-patch", kind: "detail" },
      { label: "GitHub", href: "https://github.com/yorickjue", kind: "github" },
    ],
  },
  {
    id: "project-003",
    name: "Weekend Escape Plan",
    slug: "weekend-escape-plan",
    status: "long_term",
    role: "Concept / Product Design",
    type: "web",
    summary: "一个帮助用户迅速生成周末逃离提案的轻旅行产品概念。",
    why: "我发现很多人不是不想出去，而是卡在‘去哪’和‘怎么安排’的第一步。",
    problem: "碎片时间里做旅行决策很累，尤其当用户只是想快速换个空气。",
    highlight: "把周末计划从搜索题，变成选择题。",
    featured: true,
    publishDate: "2026-04-08",
    accent: "violet",
    coverLabel: "WEB CONCEPT",
    body: [
      "这个方向很吸引我，因为它有很明确的用户情绪：人不是想做攻略，人只是想快一点离开熟悉的场景。",
      "产品表达不应该像旅行平台，而更像一个会递给你几张可能性卡片的朋友。",
      "如果继续做下去，我会优先打磨提案质量、路线解释性和整体语气。",
    ],
    links: [
      { label: "项目详情", href: "/projects/weekend-escape-plan", kind: "detail" },
      { label: "GitHub", href: "https://github.com/yorickjue", kind: "github" },
    ],
  },
  {
    id: "project-004",
    name: "Orbit Bounce",
    slug: "orbit-bounce",
    status: "done",
    role: "Game Prototype",
    type: "game",
    summary: "一个围绕球体运动反馈做出来的 2D 小游戏，用来练手也用来保留一点玩心。",
    why: "我一直想做一个足够小、但又能立刻给人反馈乐趣的交互作品。",
    problem: "很多 side project 只停在概念层，没有一个真正能玩、能感受到手感的出口。",
    highlight: "它小，但不是草率；它轻，但不是敷衍。",
    featured: false,
    publishDate: "2026-03-28",
    accent: "black",
    coverLabel: "PLAYABLE TOY",
    body: [
      "这个项目最大的价值不是商业化，而是提醒我：产品表达不一定非得严肃，也可以从‘有趣’开始。",
      "它后来变成了这次网站彩蛋设计的重要灵感来源。",
    ],
    links: [
      { label: "项目详情", href: "/projects/orbit-bounce", kind: "detail" },
      { label: "GitHub", href: "https://github.com/yorickjue", kind: "github" },
    ],
  },
];
